M48
; DRILL file {KiCad (5.99.0-10628-ga06f965ffa)} date Thu Dec  9 18:37:12 2021
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2021-12-09T18:37:12+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(5.99.0-10628-ga06f965ffa)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X129.7Y-94.4
X150.8Y-79.7
T0
M30
